include colorscheme

# Basic color configuration using the theme variables for windows and borders.
# Property Name         Border  BG      Text    Indicator Child Border
client.focused          $fg $accent $bg $accent $accent
client.focused_inactive $bg_lighter $bg_lighter $fg $comment $bg_lighter
client.unfocused        $bg_lighter $bg $fg $bg_lighter $bg_lighter
client.urgent           $error $error $bg $error $error
client.placeholder      $bg $bg $fg $bg $bg
client.background       $fg_light

# bar {
#   colors {
#     background $bg
#     separator  $bg_lighter
#     statusline $fg_dim

    # State             Border  BG      Text
#     focused_workspace   $fg $accent $bg
#     active_workspace    $fg $comment $bg
#     inactive_workspace  $comment $bg_lighter $fg
#     urgent_workspace    $error $error $bg
#     binding_mode        $bg $warning $bg
#   }
# }
