# ## Window assignment

assign [class="Gajim$"] 3
assign [class="Psi\+$"] 3
assign [class="Ekiga$"] 3
assign [app_id="telegramdesktop"] 3
assign [app_id="org.telegram.desktop"] 3
assign [app_id="io.github.tdesktop_x64.TDesktop"] 3
assign [class="Ferdium$"] 3
assign [app_id="ferdium$"] 3
assign [app_id="brave-browser$"] 2
assign [app_id="brave-browser-beta$"] 2
assign [app_id="evoution"] 4
assign [app_id="firefox$"] 2
assign [app_id="zen$"] 2
assign [app_id="thunderbird$"] 4
assign [app_id="karing$"] 10
assign [app_id="hiddify$"] 10
assign [title="Hiddify$"] 10

# for_window [app_id="^org.gnome.Nautilus$"] border pixel 2
# for_window [app_id="firefox$"] border pixel 2
# for_window [app_id="thunderbird$"] border pixel 2
# for_window [app_id="brave-browser$"] border pixel 2
# for_window [app_id="telegramdesktop"] border pixel 2
# for_window [app_id="io.github.tdesktop_x64.TDesktop"] border pixel 2

for_window [class="^Emacs" title="^Speedbar"] floating ebable # can not yet...
# Teams Brave
for_window [app_id="brave-"] border pixel 2
for_window [app_id="flameshot"] border pixel 0, floating enable, fullscreen disable

# Terminals & File managers floating
#  for_window [app_id="kitty"]                  floating enable
#  for_window [app_id="foot"]                   floating enable
#  for_window [app_id="org.wezfurlong.wezterm"] floating enable
#  for_window [app_id="Alacritty"]              floating enable
#  for_window [app_id="Thunar"] floating enable
}

# Browser popups
# https://gist.github.com/dluciv/592c630211fe77624d174ce6bd6a9e55
for_window {
  [title="^🗨 "] {
    border pixel 3, floating enable, fullscreen disable
  }
}
