# But this does not help...
# exec systemctl --user import-environment TMPDIR
#
# exec hash dbus-update-activation-environment 2>/dev/null && \
#      dbus-update-activation-environment --systemd TMPDIR

# And this too
exec export TMPDIR="$TMP"
