#!/bin/sh

zsh -il -c \
"task sync || { echo -n Sync failed. Press Enter...; read }
 todo add || { echo -n Todo add faied. Press Enter...; read }
 task sync && sleep 1 || { echo -n Sync failed. Press Enter...; read }"
