#!/bin/sh

zsh -l -c \
"task sync || { echo -n Sync failed. Press Enter...; read }
 tasksh || { echo -n TaskSH faied. Press Enter...; read }
 task sync || { echo -n Sync failed. Press Enter...; read }"
