#!/bin/sh

zsh -l -c \
"task sync || { echo -n Sync failed. Press Enter...; read }
 todo add || { echo -n Todo add faied. Press Enter...; read }
 task sync || { echo -n Sync failed. Press Enter...; read }"
