#!/bin/sh

zsh -l -c \
"task sync || { echo -n Sync failed. Press Enter...; read }
 taskwarrior-tui || { echo -n TaskWarrior-TUI faied. Press Enter...; read }
 task sync || { echo -n Sync failed. Press Enter...; read }"
