#!/bin/sh

zsh -li -c \
"task sync || { echo -n Sync failed. Press Enter...; read }
 taskwarrior-tui || { echo -n TaskWarrior-TUI faied. Press Enter...; read }
 task sync && sleep 1 || { echo -n Sync failed. Press Enter...; read }"
